Add http2
apostrophecms/mechanic pull request #35
Opened 2021-03-28 06:45 UTC by breyell

Adds http/2 support.

2021-03-29 13:51 UTC, boutell requested changes
This would be a bc break if the nginx server is too old (prior to 1.9.5), so it should be activated by an option.

Also, how has it been tested?

2021-03-29 16:30 UTC, breyell commented
I spun up a new server for mechanic testing at mechanictest.apos.dev and have been running `npm i -g apostrophecms/mechanic#branch` to update mechanic on the server to the branch I want to test.

2021-03-30 20:56 UTC, boutell requested changes
Documentation?

2021-03-30 20:58 UTC, boutell approved these changes

2021-03-30 23:26 UTC, merged